export const componentsData = [
  {
    id: 1,
    title: "WebDevelopmentBootcampsWorth",
    path: "../pages/PagesBlog/WebDevelopmentBootcampsWorth",
    cardTitle: "Are Web Development Bootcamps Worth It?",
    desc: "Explore the pros and cons of web development bootcamps and if they are a worthwhile investment.",
    img: "https://thumbor.forbes.com/thumbor/fit-in/1290x/https://www.forbes.com/advisor/wp-content/uploads/2022/06/codingbootcamps.jpeg.jpg",
    link: "/blog/WebDevelopmentBootcampsWorth",
  },
  {
    id: 2,
    title: "CanWebDevelopmentMakeYouRich",
    path: "../pages/PagesBlog/CanWebDevelopmentMakeYouRich",
    cardTitle: "Can Web Development Make You Rich?",
    desc: "Learn about the financial prospects of a career in web development.",
    img: "https://images.unsplash.com/photo-1476357471311-43c0db9fb2b4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2FuJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBNYWtlJTIwWW91JTIwUmljaCUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/CanWebDevelopmentMakeYouRich",
  },
  {
    id: 3,
    title: "CanWebDevelopmentBeASideHustle",
    path: "../pages/PagesBlog/CanWebDevelopmentBeASideHustle",
    cardTitle: "Can Web Development Be a Side Hustle?",
    desc: "Discover how web development can be a lucrative side hustle.",
    img: "https://images.unsplash.com/photo-1527784281695-866fa715d9d8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U2lkZSUyMEh1c3RsZXxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/CanWebDevelopmentBeASideHustle",
  },
  {
    id: 4,
    title: "WillWebDevelopmentBeTakenOverByAI",
    path: "../pages/PagesBlog/WillWebDevelopmentBeTakenOverByAI",
    cardTitle: "Will Web Development Be Taken Over by AI?",
    desc: "Analyze the impact of AI on the future of web development.",
    img: "https://plus.unsplash.com/premium_photo-1683288662019-c92caea8276d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwQmUlMjBUYWtlbiUyME92ZXIlMjBieSUyMEFJfGVufDB8fDB8fHww",
    link: "/blog/WillWebDevelopmentBeTakenOverByAI",
  },
  {
    id: 5,
    title: "WillWebDevelopmentBecomeObsolete",
    path: "../pages/PagesBlog/WillWebDevelopmentBecomeObsolete",
    cardTitle: "Will Web Development Become Obsolete?",
    desc: "Investigate the potential obsolescence of web development in the future.",
    img: "https://plus.unsplash.com/premium_photo-1663040543387-cb7c78c4f012?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwQmVjb21lJTIwT2Jzb2xldGUlM0Z8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WillWebDevelopmentBecomeObsolete",
  },
  {
    id: 6,
    title: "WillWebDevelopmentDieIn10Years",
    path: "../pages/PagesBlog/WillWebDevelopmentDieIn10Years",
    cardTitle: "Will Web Development Die in 10 Years?",
    desc: "Explore the future of web development and its potential longevity.",
    img: "https://plus.unsplash.com/premium_photo-1682125189109-eaf17ac93b9c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwRGllJTIwaW4lMjAxMCUyMFllYXJzJTNGfGVufDB8fDB8fHww",
    link: "/blog/WillWebDevelopmentDieIn10Years",
  },
  {
    id: 7,
    title: "WillWebDevelopmentBeReplacedByAI",
    path: "../pages/PagesBlog/WillWebDevelopmentBeReplacedByAI",
    cardTitle: "Will Web Development Be Replaced by AI?",
    desc: "Examine whether AI will replace web developers in the near future.",
    img: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/blog/WillWebDevelopmentBeReplacedByAI",
  },
  {
    id: 8,
    title: "WhoIsWebDevelopment",
    path: "../pages/PagesBlog/WhoIsWebDevelopment",
    cardTitle: "Who Is Web Development For?",
    desc: "Understand who can benefit from learning web development.",
    img: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2hvJTIwSXMlMjBXZWIlMjBEZXZlbG9wbWVudCUyMEZvciUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhoIsWebDevelopment",
  },
  {
    id: 9,
    title: "WhoCanLearnWebDevelopment",
    path: "../pages/PagesBlog/WhoCanLearnWebDevelopment",
    cardTitle: "Who Can Learn Web Development?",
    desc: "Discover who can learn and excel in web development.",
    img: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhoCanLearnWebDevelopment",
  },
  {
    id: 10,
    title: "WhyWebDevelopmentIsImportant",
    path: "../pages/PagesBlog/WhyWebDevelopmentIsImportant",
    cardTitle: "Why Web Development Is Important",
    desc: "Learn about the significance of web development in today's world.",
    img: "https://images.unsplash.com/reserve/LJIZlzHgQ7WPSh5KVTCB_Typewriter.jpg?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8V2h5JTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBJcyUyMEltcG9ydGFudHxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhyWebDevelopmentIsImportant",
  },
  {
    id: 11,
    title: "WhyWebDevelopmentIsInDemand",
    path: "../pages/PagesBlog/WhyWebDevelopmentIsInDemand",
    cardTitle: "Why Web Development Is in Demand",
    desc: "Explore why web development skills are highly sought after.",
    img: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhyWebDevelopmentIsInDemand",
  },
  {
    id: 12,
    title: "WhichWebDevelopmentCourseIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentCourseIsBest",
    cardTitle: "Which Web Development Course Is Best?",
    desc: "Find out which web development courses are the best options for learning.",
    img: "https://plus.unsplash.com/premium_photo-1664299935896-8b7638a6f105?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fFdoaWNoJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBDb3Vyc2UlMjBJcyUyMEJlc3R8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WhichWebDevelopmentCourseIsBest",
  },
  {
    id: 13,
    title: "WhichWebDevelopmentLanguageIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentLanguageIsBest",
    cardTitle: "Which Web Development Language Is Best?",
    desc: "Discover the best programming languages for web development.",
    img: "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fFdoaWNoJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBMYW5ndWFnZSUyMElzJTIwQmVzdCUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhichWebDevelopmentLanguageIsBest",
  },
  {
    id: 14,
    title: "WhichWebDevelopmentFrameworkIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentFrameworkIsBest",
    cardTitle: "Which Web Development Framework Is Best?",
    desc: "Learn about the top frameworks for web development.",
    img: "https://images.unsplash.com/photo-1472954253026-157558836cd2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8RnJhbWV3b3JrfGVufDB8fDB8fHww",
    link: "/blog/WhichWebDevelopmentFrameworkIsBest",
  },
  {
    id: 15,
    title: "WhichWebDevelopmentIsInDemand",
    path: "../pages/PagesBlog/WhichWebDevelopmentIsInDemand",
    cardTitle: "Which Web Development Skills Are in Demand?",
    desc: "Find out which web development skills are currently in high demand.",
    img: "https://plus.unsplash.com/premium_photo-1667518286137-6f01cd8c2fea?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8RGV2ZWxvcG1lbnQlMjBTa2lsbHN8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WhichWebDevelopmentIsInDemand",
  },
  {
    id: 16,
    title: "WhereToLearnWebDevelopment",
    path: "../pages/PagesBlog/WhereToLearnWebDevelopment",
    cardTitle: "Where to Learn Web Development",
    desc: "Explore the best places to learn web development online and offline.",
    img: "https://images.unsplash.com/photo-1503551723145-6c040742065b-v2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8TGVhcm4lMjBXZWIlMjBEZXZlbG9wbWVudHxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhereToLearnWebDevelopment",
  },
  {
    id: 17,
    title: "WhereToPracticeWebDevelopment",
    path: "../pages/PagesBlog/WhereToPracticeWebDevelopment",
    cardTitle: "Where to Practice Web Development",
    desc: "Find out where you can practice and improve your web development skills.",
    img: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fFByYWN0aWNlJTIwV2ViJTIwRGV2ZWxvcG1lbnR8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WhereToPracticeWebDevelopment",
  },
  {
    id: 18,
    title: "WhatWebDevelopmentDo",
    path: "../pages/PagesBlog/WhatWebDevelopmentDo",
    cardTitle: "What Does Web Development Do?",
    desc: "Understand the role and impact of web development in various industries.",
    img: "https://images.unsplash.com/photo-1636633762833-5d1658f1e29b?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8V2hhdCUyMERvZXMlMjBXZWIlMjBEZXZlbG9wbWVudCUyMERvJTNGfGVufDB8fDB8fHww",
    link: "/blog/WhatWebDevelopmentDo",
  },
  {
    id: 19,
    title: "AreBusinessExpensesTaxDeductible",
    path: "../pages/PagesBlog/AreBusinessExpensesTaxDeductible",
    cardTitle: "Are Business Expenses Tax Deductible?",
    desc: "Learn about the tax deductibility of business expenses.",
    img: "https://plus.unsplash.com/premium_photo-1677865215827-500033951a6b?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VGF4JTIwRGVkdWN0aWJsZSUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/AreBusinessExpensesTaxDeductible",
  },
  {
    id: 20,
    title: "WhatBusinessToStart",
    path: "../pages/PagesBlog/WhatBusinessToStart",
    cardTitle: "What Business to Start?",
    desc: "Get insights into choosing the right business to start.",
    img: "https://images.unsplash.com/photo-1665686304355-0b09b1e3b03c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fEJ1c2luZXNzfGVufDB8fDB8fHww",
    link: "/blog/WhatBusinessToStart",
  },
  {
    id: 21,
    title: "WhatBusinessShouldIStart",
    path: "../pages/PagesBlog/WhatBusinessShouldIStart",
    cardTitle: "What Business Should I Start?",
    desc: "Discover various business ideas and find out which one suits you best.",
    img: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhatBusinessShouldIStart",
  },
  {
    id: 22,
    title: "WhatBusinessMakesTheMostMoney",
    path: "../pages/PagesBlog/WhatBusinessMakesTheMostMoney",
    cardTitle: "What Business Makes the Most Money?",
    desc: "Explore the most profitable business ventures.",
    img: "https://images.unsplash.com/photo-1515606378517-3451a4fa2e12?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8dGhlJTIwTW9zdCUyME1vbmV5fGVufDB8fDB8fHww",
    link: "/blog/WhatBusinessMakesTheMostMoney",
  },
  {
    id: 23,
    title: "WhatUiUxDesignerDo",
    path: "../pages/PagesBlog/WhatUiUxDesignerDo",
    cardTitle: "What Does a UI/UX Designer Do?",
    desc: "Understand the role and responsibilities of a UI/UX designer.",
    img: "https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhatUiUxDesignerDo",
  },
  {
    id: 24,
    title: "WhatIsUiUxDesignerSalary",
    path: "../pages/PagesBlog/WhatIsUiUxDesignerSalary",
    cardTitle: "What Is a UI/UX Designer's Salary?",
    desc: "Find out about the earning potential of UI/UX designers.",
    img: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2hhdCUyMElzJTIwYSUyMFVJJTJGVVglMjBEZXNpZ25lcidzJTIwU2FsYXJ5JTNGfGVufDB8fDB8fHww",
    link: "/blog/WhatIsUiUxDesignerSalary",
  },
  {
    id: 25,
    title: "HowToBecomeUiUxDesignerAfter12th",
    path: "../pages/PagesBlog/HowToBecomeUiUxDesignerAfter12th",
    cardTitle: "How to Become a UI/UX Designer After 12th",
    desc: "Learn the steps to become a UI/UX designer right after high school.",
    img: "https://images.unsplash.com/photo-1676282824845-b6c1ccb75888?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8SG93JTIwdG8lMjBCZWNvbWV8ZW58MHx8MHx8fDA%3D",
    link: "/blog/HowToBecomeUiUxDesignerAfter12th",
  },
];
