export const componentsData = [
  {
    id: 1,
    title: "WebDevelopmentBootcampsWorth",
    path: "../pages/PagesBlog/WebDevelopmentBootcampsWorth",
    cardTitle: "Are Web Development Bootcamps Worth It?",
    desc: "Explore the pros and cons of web development bootcamps and if they are a worthwhile investment.",
    img: "https://thumbor.forbes.com/thumbor/fit-in/1290x/https://www.forbes.com/advisor/wp-content/uploads/2022/06/codingbootcamps.jpeg.jpg",
    link: "/blog/WebDevelopmentBootcampsWorth",
  },
  {
    id: 2,
    title: "CanWebDevelopmentMakeYouRich",
    path: "../pages/PagesBlog/CanWebDevelopmentMakeYouRich",
    cardTitle: "Can Web Development Make You Rich?",
    desc: "Learn about the financial prospects of a career in web development.",
    img: "https://images.unsplash.com/photo-1476357471311-43c0db9fb2b4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2FuJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBNYWtlJTIwWW91JTIwUmljaCUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/CanWebDevelopmentMakeYouRich",
  },
  {
    id: 3,
    title: "CanWebDevelopmentBeASideHustle",
    path: "../pages/PagesBlog/CanWebDevelopmentBeASideHustle",
    cardTitle: "Can Web Development Be a Side Hustle?",
    desc: "Discover how web development can be a lucrative side hustle.",
    img: "https://images.unsplash.com/photo-1527784281695-866fa715d9d8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U2lkZSUyMEh1c3RsZXxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/CanWebDevelopmentBeASideHustle",
  },
  {
    id: 4,
    title: "WillWebDevelopmentBeTakenOverByAI",
    path: "../pages/PagesBlog/WillWebDevelopmentBeTakenOverByAI",
    cardTitle: "Will Web Development Be Taken Over by AI?",
    desc: "Analyze the impact of AI on the future of web development.",
    img: "https://plus.unsplash.com/premium_photo-1683288662019-c92caea8276d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwQmUlMjBUYWtlbiUyME92ZXIlMjBieSUyMEFJfGVufDB8fDB8fHww",
    link: "/blog/WillWebDevelopmentBeTakenOverByAI",
  },
  {
    id: 5,
    title: "WillWebDevelopmentBecomeObsolete",
    path: "../pages/PagesBlog/WillWebDevelopmentBecomeObsolete",
    cardTitle: "Will Web Development Become Obsolete?",
    desc: "Investigate the potential obsolescence of web development in the future.",
    img: "https://plus.unsplash.com/premium_photo-1663040543387-cb7c78c4f012?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwQmVjb21lJTIwT2Jzb2xldGUlM0Z8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WillWebDevelopmentBecomeObsolete",
  },
  {
    id: 6,
    title: "WillWebDevelopmentDieIn10Years",
    path: "../pages/PagesBlog/WillWebDevelopmentDieIn10Years",
    cardTitle: "Will Web Development Die in 10 Years?",
    desc: "Explore the future of web development and its potential longevity.",
    img: "https://plus.unsplash.com/premium_photo-1682125189109-eaf17ac93b9c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8V2lsbCUyMFdlYiUyMERldmVsb3BtZW50JTIwRGllJTIwaW4lMjAxMCUyMFllYXJzJTNGfGVufDB8fDB8fHww",
    link: "/blog/WillWebDevelopmentDieIn10Years",
  },
  {
    id: 7,
    title: "WillWebDevelopmentBeReplacedByAI",
    path: "../pages/PagesBlog/WillWebDevelopmentBeReplacedByAI",
    cardTitle: "Will Web Development Be Replaced by AI?",
    desc: "Examine whether AI will replace web developers in the near future.",
    img: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "/blog/WillWebDevelopmentBeReplacedByAI",
  },
  {
    id: 8,
    title: "WhoIsWebDevelopment",
    path: "../pages/PagesBlog/WhoIsWebDevelopment",
    cardTitle: "Who Is Web Development For?",
    desc: "Understand who can benefit from learning web development.",
    img: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2hvJTIwSXMlMjBXZWIlMjBEZXZlbG9wbWVudCUyMEZvciUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhoIsWebDevelopment",
  },
  {
    id: 9,
    title: "WhoCanLearnWebDevelopment",
    path: "../pages/PagesBlog/WhoCanLearnWebDevelopment",
    cardTitle: "Who Can Learn Web Development?",
    desc: "Discover who can learn and excel in web development.",
    img: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhoCanLearnWebDevelopment",
  },
  {
    id: 10,
    title: "WhyWebDevelopmentIsImportant",
    path: "../pages/PagesBlog/WhyWebDevelopmentIsImportant",
    cardTitle: "Why Web Development Is Important",
    desc: "Learn about the significance of web development in today's world.",
    img: "https://images.unsplash.com/reserve/LJIZlzHgQ7WPSh5KVTCB_Typewriter.jpg?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8V2h5JTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBJcyUyMEltcG9ydGFudHxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhyWebDevelopmentIsImportant",
  },
  {
    id: 11,
    title: "WhyWebDevelopmentIsInDemand",
    path: "../pages/PagesBlog/WhyWebDevelopmentIsInDemand",
    cardTitle: "Why Web Development Is in Demand",
    desc: "Explore why web development skills are highly sought after.",
    img: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDF8fHdicyUyMGRldmVsb3BtZW50fGVufDB8fHx8MTY4MDg5MzI3MQ&ixlib=rb-1.2.1&q=80&w=400",
    link: "/blog/WhyWebDevelopmentIsInDemand",
  },
  {
    id: 12,
    title: "WhichWebDevelopmentCourseIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentCourseIsBest",
    cardTitle: "Which Web Development Course Is Best?",
    desc: "Find out which web development courses are the best options for learning.",
    img: "https://plus.unsplash.com/premium_photo-1664299935896-8b7638a6f105?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fFdoaWNoJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBDb3Vyc2UlMjBJcyUyMEJlc3R8ZW58MHx8MHx8fDA%3D",
    link: "/blog/WhichWebDevelopmentCourseIsBest",
  },
  {
    id: 13,
    title: "WhichWebDevelopmentLanguageIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentLanguageIsBest",
    cardTitle: "Which Web Development Language Is Best?",
    desc: "Discover the best programming languages for web development.",
    img: "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fFdoaWNoJTIwV2ViJTIwRGV2ZWxvcG1lbnQlMjBMYW5ndWFnZSUyMElzJTIwQmVzdCUzRnxlbnwwfHwwfHx8MA%3D%3D",
    link: "/blog/WhichWebDevelopmentLanguageIsBest",
  },
  {
    id: 14,
    title: "WhichWebDevelopmentFrameworkIsBest",
    path: "../pages/PagesBlog/WhichWebDevelopmentFrameworkIsBest",
    cardTitle: "Which Web Development Framework Is Best?",
    desc: "Learn about the top frameworks for web development.",
    img: "https://images.unsplash.com/photo-1472954253026-157558836cd2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8RnJhbWV3b3JrfGVufDB8fDB8fHww",
    link: "/blog/WhichWebDevelopmentFrameworkIsBest",
  },
];
